language: r
sudo: false
cache: packages

matrix:
  include:
    - os: linux
      dist: trusty
      r: release
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libgsl-dev
            - libmpfr-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - _R_CHECK_FORCE_SUGGESTS_=false

before_install:
  - mkdir -p ~/.R/
  - echo "CXX14=g++-7 -std=c++1y -fPIC" >> ~/.R/Makevars
