language: r
sudo: false
cache: packages
dist: trusty

latex: true



matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libgsl-dev
            - libmpfr-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - mkdir -p ~/.R/
  - echo "CXX14 = g++-7 -fPIC -flto=2" >> ~/.R/Makevars

script:
  - |
    travis_wait 42 R CMD build .
    travis_wait 59 R CMD check bfvartest*tar.gz

after_script:
  - tar -ztvf bfvartest_*.tar.gz
  - echo ${NOT_CRAN}

after_success:
  - travis_wait 40 tar -C .. -xf $PKG_TARBALL

after_failure:
  - cat bfvartest.Rcheck/00*
