language: r
cache: packages
r_check_args: '--as-cran'
r_build_args: '--no-manual'

jobs:
  include:
    - os: linux
      dist: xenial
      latex: false
      r: release
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libgsl-dev
            - libmpfr-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - _R_CHECK_FORCE_SUGGESTS_=false

before_install:
  - mkdir -p ~/.R/
  - echo "CXX14=g++-7 -std=c++1y -fPIC" >> ~/.R/Makevars

script:
  - |
    travis_wait 42 R CMD build .
    travis_wait 70 R CMD check bfvartest*tar.gz
